from __future__ import annotations
import re
import unicodedata
from dataclasses import dataclass, field
from typing import Dict, List, Tuple, Optional

try:
    import ahocorasick
    _AHO_AVAILABLE = True
except ImportError:
    _AHO_AVAILABLE = False

@dataclass
class KeywordEntry:
    keyword: str
    weight: int = 5
    synonyms: List[str] = field(default_factory=list)

@dataclass
class TaxonomyEntry:
    name: str
    keywords: List[KeywordEntry]
    priority: int = 5
    activation_score: float = 5.0
    min_strong_keywords: int = 0
    parent: Optional[str] = None

W_NOISE, W_WEAK, W_MODERATE, W_STRONG, W_DEFINITIVE = 1, 2, 4, 7, 10
_kw = lambda k, w=W_STRONG, s=None: KeywordEntry(keyword=k, weight=w, synonyms=s or [])

TAXONOMY: List[TaxonomyEntry] = [
    TaxonomyEntry(name="SAS Experience", priority=8, activation_score=8, min_strong_keywords=1, keywords=[_kw("Base SAS", W_DEFINITIVE), _kw("Statistical Analysis System", W_DEFINITIVE), _kw("SAS functions", W_DEFINITIVE, ["SAS function"]), _kw("PROC IMPORT", W_STRONG, ["PROC-IMPORT", "PROC_IMPORT"]), _kw("PROC EXPORT", W_STRONG, ["PROC-EXPORT", "PROC_EXPORT"]), _kw("PROC SORT", W_STRONG, ["PROC-SORT", "PROC_SORT"]), _kw("PROC DATASETS", W_STRONG, ["PROC-DATASETS", "PROC_DATASETS"]), _kw("PROC SQL", W_STRONG, ["PROC-SQL", "PROC_SQL", "PROC/SQL"]), _kw("PROC MEANS", W_STRONG, ["PROC-MEANS", "PROC_MEANS"]), _kw("PROC SUMMARY", W_STRONG, ["PROC-SUMMARY", "PROC_SUMMARY"]), _kw("PROC FREQ", W_STRONG, ["PROC-FREQ", "PROC_FREQ"]), _kw("PROC UNIVARIATE", W_STRONG), _kw("PROC ANOVA", W_STRONG), _kw("PROC GLM", W_STRONG), _kw("PROC REG", W_STRONG), _kw("PROC LOGISTIC", W_STRONG), _kw("PROC MIXED", W_STRONG), _kw("PROC PHREG", W_STRONG), _kw("PROC LIFETEST", W_STRONG), _kw("PROC TRANSPOSE", W_STRONG), _kw("PROC FORMAT", W_STRONG), _kw("PROC APPEND", W_STRONG), _kw("PROC PRINT", W_STRONG), _kw("PROC REPORT", W_STRONG), _kw("PROC TABULATE", W_STRONG), _kw("PROC CHART", W_STRONG), _kw("PROC SGPLOT", W_STRONG), _kw("PROC SGSCATTER", W_STRONG), _kw("PROC GCHART", W_STRONG), _kw("PROC GPLOT", W_STRONG), _kw("PROC GREPLAY", W_STRONG), _kw("PROC TTEST", W_STRONG, ["PROC T-TEST", "PROC T TEST"]), _kw("PROC CORR", W_STRONG), _kw("PROC FACTOR", W_STRONG), _kw("PROC DISCRIM", W_STRONG), _kw("PROC CLUSTER", W_STRONG), _kw("PROC NPAR1WAY", W_STRONG), _kw("PROC LATTICE", W_STRONG), _kw("PROC STEPDISC", W_STRONG), _kw("PROC ARIMA", W_STRONG), _kw("PROC EXPAND", W_STRONG), _kw("PROC PANEL", W_STRONG), _kw("Macros", W_MODERATE, ["SAS Macros", "SAS macro"]), _kw("TFL", W_MODERATE), _kw("statistical methods", W_MODERATE), _kw("statistical techniques", W_MODERATE), _kw("descriptive statistics", W_MODERATE), _kw("hypothesis testing", W_MODERATE), _kw("regression analysis", W_MODERATE), _kw("survival analysis", W_MODERATE), _kw("non-parametric methods", W_MODERATE), _kw("SUBSTR", W_WEAK), _kw("UPCASE", W_WEAK), _kw("LOWCASE", W_WEAK), _kw("CATS", W_WEAK), _kw("STRIP", W_WEAK), _kw("SCAN", W_WEAK), _kw("TRIM", W_WEAK), _kw("INPUT", W_NOISE), _kw("MEAN", W_NOISE), _kw("MAX", W_NOISE), _kw("MIN", W_NOISE), _kw("ROUND", W_NOISE), _kw("CAT", W_NOISE), _kw("INDEX", W_NOISE), _kw("LENGTH", W_NOISE), _kw("YEAR", W_NOISE), _kw("MONTH", W_NOISE), _kw("DAY", W_NOISE), _kw("PUT", W_NOISE)]),
    TaxonomyEntry(name="R Experience", priority=7, activation_score=7, min_strong_keywords=1, keywords=[_kw("R Programming", W_DEFINITIVE, ["R programming language"]), _kw("Statistical analysis using R", W_DEFINITIVE), _kw("Visualization using R", W_DEFINITIVE), _kw("R Packages", W_STRONG, ["R package"]), _kw("ggplot2", W_STRONG), _kw("dplyr", W_STRONG), _kw("tidyr", W_STRONG), _kw("data.table", W_STRONG), _kw("randomForest", W_STRONG), _kw("shiny", W_STRONG), _kw("rmarkdown", W_STRONG), _kw("Rcpp", W_STRONG), _kw("glmnet", W_STRONG), _kw("caret", W_MODERATE), _kw("lubridate", W_MODERATE), _kw("plotly", W_MODERATE), _kw("tibble", W_MODERATE), _kw("reshape2", W_MODERATE), _kw("magrittr", W_MODERATE), _kw("stringr", W_MODERATE), _kw("readr", W_MODERATE), _kw("knitr", W_MODERATE), _kw("forecast", W_MODERATE), _kw("readxl", W_MODERATE), _kw("Data Manipulation", W_WEAK), _kw("R", W_WEAK)]),
    TaxonomyEntry(name="TA Experience", priority=6, activation_score=5, keywords=[_kw("CARDIOLOGY", W_DEFINITIVE), _kw("ONCOLOGY", W_DEFINITIVE), _kw("NEUROLOGY", W_DEFINITIVE), _kw("PSYCHIATRY", W_DEFINITIVE), _kw("ENDOCRINOLOGY", W_DEFINITIVE), _kw("RHEUMATOLOGY", W_DEFINITIVE), _kw("GASTROENTEROLOGY", W_DEFINITIVE), _kw("PULMONOLOGY", W_DEFINITIVE), _kw("DERMATOLOGY", W_DEFINITIVE), _kw("NEPHROLOGY", W_DEFINITIVE), _kw("HEMATOLOGY", W_DEFINITIVE), _kw("INFECTIOUS DISEASES", W_DEFINITIVE), _kw("ALLERGY AND IMMUNOLOGY", W_DEFINITIVE), _kw("UROLOGY", W_DEFINITIVE), _kw("OBSTETRICS AND GYNECOLOGY", W_DEFINITIVE), _kw("PEDIATRICS", W_DEFINITIVE), _kw("ORTHOPEDICS", W_DEFINITIVE), _kw("GERIATRICS", W_DEFINITIVE), _kw("OPHTHALMOLOGY", W_DEFINITIVE), _kw("RADIOLOGY", W_DEFINITIVE), _kw("ANESTHESIOLOGY", W_DEFINITIVE), _kw("EMERGENCY MEDICINE", W_DEFINITIVE), _kw("PHYSICAL MEDICINE AND REHABILITATION", W_DEFINITIVE), _kw("SLEEP MEDICINE", W_DEFINITIVE), _kw("PAIN MANAGEMENT", W_DEFINITIVE), _kw("TRANSPLANTATION", W_DEFINITIVE), _kw("IMMUNOLOGY", W_STRONG), _kw("VACCINES", W_STRONG), _kw("ONC", W_MODERATE), _kw("CV", W_MODERATE), _kw("NS", W_MODERATE), _kw("CNS", W_MODERATE), _kw("TA", W_WEAK)]),
    TaxonomyEntry(name="Phase1 experience", priority=7, activation_score=7, min_strong_keywords=1, keywords=[_kw("PHARMACOKINETICS", W_DEFINITIVE, ["pharmacokinetic"]), _kw("PHARMACODYNAMICS", W_DEFINITIVE, ["pharmacodynamic"]), _kw("PK/PD", W_DEFINITIVE, ["PK-PD", "PK PD"]), _kw("POPULATION PK", W_DEFINITIVE, ["POP PK", "PopPK"]), _kw("WINNOLIN", W_DEFINITIVE), _kw("WINOLIN", W_DEFINITIVE), _kw("PHEONIX", W_DEFINITIVE), _kw("PK MERGE", W_STRONG), _kw("DM PK", W_STRONG), _kw("PHASE I", W_STRONG, ["PHASE 1"]), _kw("PHASE I-IV", W_MODERATE, ["PHASE 1-4"]), _kw("PK", W_MODERATE), _kw("PD", W_MODERATE)]),
    TaxonomyEntry(name="Phase II - IV", priority=7, activation_score=6, keywords=[_kw("Phase II - IV", W_DEFINITIVE, ["Phase II-IV", "Phase 2-4"]), _kw("Phase I, II and III", W_DEFINITIVE, ["Phase I, II, III"]), _kw("PHASE III", W_DEFINITIVE), _kw("PHASE IV", W_DEFINITIVE, ["PHASE 4"]), _kw("Phase II", W_STRONG, ["PHASE 2"]), _kw("PHASE I-IV", W_STRONG, ["PHASE 1-4", "PHASE 2-4", "PHASE 1 - 4"]), _kw("adaptive trial designs", W_STRONG), _kw("interim analysis", W_STRONG), _kw("Efficacy endpoints", W_STRONG), _kw("overall survival", W_STRONG), _kw("disease-specific endpoints", W_STRONG), _kw("longitudinal data analysis", W_MODERATE), _kw("subgroup analysis", W_MODERATE), _kw("hypothesis testing", W_MODERATE), _kw("Regression analysis", W_MODERATE), _kw("survival analysis", W_MODERATE)]),
    TaxonomyEntry(name="SDTM Experience", priority=9, activation_score=8, min_strong_keywords=1, keywords=[_kw("Study Data Tabulation Model", W_DEFINITIVE), _kw("SDTM", W_DEFINITIVE), _kw("SDTM Specifications", W_DEFINITIVE), _kw("Adverse events", W_STRONG), _kw("Concomitant medications", W_STRONG), _kw("Laboratory tests", W_STRONG), _kw("vital signs", W_STRONG), _kw("Demographic information", W_STRONG), _kw("Medical history", W_MODERATE), _kw("Exposure as collected", W_STRONG), _kw("Substance use", W_MODERATE), _kw("Protocol deviations", W_STRONG), _kw("Healthcare encounters", W_STRONG), _kw("Drug accountability", W_STRONG), _kw("Death details", W_STRONG), _kw("Ecg test results", W_STRONG, ["ECG test results"]), _kw("exclusion criterion not met", W_STRONG), _kw("Immunogenicity specimen assessments", W_STRONG), _kw("Pk concentrations", W_STRONG), _kw("Pk parameters", W_STRONG), _kw("Physical examination", W_STRONG), _kw("Subject characteristics", W_MODERATE), _kw("Subject status", W_MODERATE), _kw("Findings about", W_MODERATE), _kw("Trial arms", W_MODERATE), _kw("Trial elements", W_MODERATE), _kw("Trial visits", W_MODERATE), _kw("Trial inclusion", W_MODERATE), _kw("exclusion criteria", W_MODERATE), _kw("Trial summary", W_MODERATE), _kw("ECG", W_MODERATE), _kw("AE", W_MODERATE), _kw("CM", W_MODERATE), _kw("LB", W_MODERATE), _kw("VS", W_MODERATE), _kw("DM", W_MODERATE), _kw("MH", W_WEAK), _kw("CO", W_WEAK), _kw("SE", W_WEAK), _kw("SV", W_WEAK), _kw("EC", W_WEAK), _kw("EX", W_WEAK), _kw("SU", W_WEAK), _kw("PR", W_WEAK), _kw("CE", W_WEAK), _kw("DS", W_WEAK), _kw("DV", W_WEAK), _kw("HO", W_WEAK), _kw("DA", W_WEAK), _kw("DD", W_WEAK), _kw("EG", W_WEAK), _kw("IE", W_WEAK), _kw("IS", W_WEAK), _kw("PC", W_WEAK), _kw("PP", W_WEAK), _kw("PE", W_WEAK), _kw("SC", W_WEAK), _kw("SS", W_WEAK), _kw("FA", W_WEAK), _kw("TA", W_NOISE), _kw("TE", W_NOISE), _kw("TS", W_NOISE), _kw("TV", W_NOISE), _kw("TI", W_NOISE), _kw("Exposure", W_NOISE), _kw("Procedures", W_NOISE), _kw("Disposition", W_NOISE), _kw("Inclusion", W_NOISE), _kw("Demographics", W_NOISE), _kw("Subject elements", W_NOISE), _kw("Subject visits", W_NOISE)]),
    TaxonomyEntry(name="SDTM Specifications", priority=9, activation_score=8, parent="SDTM Experience", keywords=[_kw("SDTM SPECIFICATIONS", W_DEFINITIVE, ["SDTM SPECIFICATION"]), _kw("SDTM SPECS", W_DEFINITIVE, ["SDTM SPEC"]), _kw("SDTM SPECIFICATIONS DEVELOPMENT", W_DEFINITIVE), _kw("SDTM SPECS DEVELOPMENT", W_DEFINITIVE), _kw("SDTM SPECIFICATION DEVELOPMENT", W_DEFINITIVE)]),
    TaxonomyEntry(name="aCRF", priority=7, activation_score=5, keywords=[_kw("aCRF", W_DEFINITIVE), _kw("CRF annotations", W_DEFINITIVE), _kw("Case Report Forms", W_STRONG), _kw("CRF", W_MODERATE), _kw("Annotations", W_NOISE)]),
    TaxonomyEntry(name="Complex SDTM domains", priority=8, activation_score=7, parent="SDTM Experience", keywords=[_kw("Reproductive system findings", W_DEFINITIVE), _kw("Tumor identification", W_DEFINITIVE), _kw("Tumor response", W_DEFINITIVE), _kw("Disease response", W_STRONG), _kw("Skin response", W_STRONG), _kw("Trial disease assessment", W_STRONG), _kw("Microbiology specimen", W_STRONG), _kw("Microscopic findings", W_STRONG), _kw("Microbiology susceptibility test", W_STRONG), _kw("Questionnaires", W_MODERATE), _kw("Morphology", W_MODERATE), _kw("RP", W_WEAK), _kw("RS", W_WEAK), _kw("TU", W_WEAK), _kw("TR", W_WEAK), _kw("SR", W_WEAK), _kw("TD", W_WEAK), _kw("MB", W_WEAK), _kw("MI", W_WEAK), _kw("MO", W_WEAK), _kw("MS", W_WEAK), _kw("QS", W_WEAK)]),
    TaxonomyEntry(name="ADaM Experience", priority=9, activation_score=7, min_strong_keywords=1, keywords=[_kw("ADaM", W_DEFINITIVE, ["ADAM"]), _kw("ADSL", W_DEFINITIVE), _kw("ADTTE", W_DEFINITIVE), _kw("ADAE", W_DEFINITIVE), _kw("ADLB", W_DEFINITIVE), _kw("ADPC", W_STRONG), _kw("ADEFF", W_STRONG), _kw("ADPP", W_STRONG), _kw("ADVS", W_STRONG), _kw("ADEG", W_STRONG)]),
    TaxonomyEntry(name="ADaM Specifications", priority=9, activation_score=8, parent="ADaM Experience", keywords=[_kw("ADaM SPECIFICATIONS", W_DEFINITIVE, ["ADaM SPECIFICATION"]), _kw("ADaM SPECS", W_DEFINITIVE, ["ADaM SPEC"]), _kw("ADaM SPECIFICATIONS DEVELOPMENT", W_DEFINITIVE), _kw("ADaM SPECS DEVELOPMENT", W_DEFINITIVE), _kw("ADaM SPECIFICATION DEVELOPMENT", W_DEFINITIVE)]),
    TaxonomyEntry(name="ADEFF", priority=8, activation_score=7, parent="ADaM Experience", keywords=[_kw("ADEFF", W_DEFINITIVE), _kw("ADTTE", W_DEFINITIVE), _kw("ADRS", W_STRONG), _kw("ADQS", W_STRONG), _kw("ADPP", W_STRONG), _kw("ADPC", W_STRONG), _kw("Integrated Summaries of Efficacy", W_STRONG), _kw("integrated summary of efficacy", W_STRONG), _kw("ISE", W_MODERATE)]),
    TaxonomyEntry(name="TP experience", priority=6, activation_score=5, keywords=[_kw("DATABASE LOCKS", W_STRONG), _kw("LEADING STUDY", W_STRONG), _kw("LEADING TRIAL", W_STRONG), _kw("REVIEW DATA TRANSFER SPECIFICATIONS", W_STRONG), _kw("REVIEW DTS", W_STRONG), _kw("INTERIM ANALYSIS", W_MODERATE), _kw("DBL", W_MODERATE), _kw("ADHOC", W_MODERATE), _kw("Dry Runs", W_MODERATE)]),
    TaxonomyEntry(name="CTT meetings", priority=5, activation_score=5, keywords=[_kw("CLINICAL TRIAL MEETINGS", W_DEFINITIVE), _kw("CTT meetings", W_DEFINITIVE)]),
    TaxonomyEntry(name="SDRG/ADRG", priority=7, activation_score=5, keywords=[_kw("Summary of Clinical Study Reports (SDRG)", W_DEFINITIVE), _kw("Analysis Data Reviewer's Guide (ADRG)", W_DEFINITIVE), _kw("ADRG", W_DEFINITIVE), _kw("SDRG", W_DEFINITIVE), _kw("study completion documents", W_STRONG), _kw("Reviewer guide", W_MODERATE), _kw("Reviewer guidelines", W_MODERATE)]),
    TaxonomyEntry(name="Project level", priority=6, activation_score=5, keywords=[_kw("PROJECT LEVEL MACROS", W_DEFINITIVE), _kw("project level standards", W_STRONG), _kw("therapeutic areas standards", W_STRONG), _kw("program level", W_MODERATE)]),
    TaxonomyEntry(name="Pooling SCS", priority=7, activation_score=7, keywords=[_kw("INTEGRATED SUMMARY SAFETY", W_DEFINITIVE, ["ISS"]), _kw("SUMMARY CLINICAL SAFETY", W_DEFINITIVE), _kw("Pooling", W_MODERATE), _kw("SCS", W_MODERATE), _kw("ISS", W_MODERATE)]),
    TaxonomyEntry(name="Pooling SCE", priority=7, activation_score=7, keywords=[_kw("INTEGRATED SUMMARY EFFICACY", W_DEFINITIVE, ["ISE"]), _kw("SUMMARY CLINICAL EFFICACY", W_DEFINITIVE), _kw("Pooling", W_MODERATE), _kw("SCE", W_MODERATE), _kw("ISE", W_MODERATE)]),
    TaxonomyEntry(name="Define.xml", priority=8, activation_score=7, keywords=[_kw("DEFINE.XML", W_DEFINITIVE, ["define.xml", "define xml"]), _kw("PINNACLE 21", W_DEFINITIVE, ["Pinnacle21"]), _kw("OPEN CDISC CHECKS", W_DEFINITIVE), _kw("VARIABLE LEVEL METADATA", W_STRONG), _kw("VALUE LEVEL METADATA", W_STRONG), _kw("ANNOTATED CRF", W_STRONG), _kw("CODE LIST", W_MODERATE, ["codelist", "code-list"]), _kw("P21", W_MODERATE), _kw("Reviewer guide", W_WEAK), _kw("Reviewer guidelines", W_WEAK)]),
    TaxonomyEntry(name="DSUR/PSUR/DSMB/DMC/RMP", priority=7, activation_score=7, keywords=[_kw("DEVELOPMENT SAFETY UPDATE REPORT", W_DEFINITIVE, ["DSUR"]), _kw("PERIODIC SAFETY UPDATE REPORT", W_DEFINITIVE, ["PSUR"]), _kw("DSUR", W_DEFINITIVE), _kw("PSUR", W_DEFINITIVE), _kw("DSMB", W_STRONG), _kw("DMC", W_STRONG), _kw("RMP", W_STRONG)]),
    TaxonomyEntry(name="Safety", priority=7, activation_score=7, keywords=[_kw("ADVERSE EVENT TABLES", W_DEFINITIVE), _kw("ADVERSE EVENTS REPORTS", W_DEFINITIVE), _kw("SHIFT TABLES", W_STRONG), _kw("SAFETY REPORTS", W_STRONG), _kw("SAFETY TABLES", W_STRONG), _kw("change from baseline tables", W_STRONG), _kw("summary characteristic", W_MODERATE), _kw("SUMMARIES", W_NOISE)]),
    TaxonomyEntry(name="Efficacy", priority=7, activation_score=7, keywords=[_kw("EFFICACY TABLES", W_DEFINITIVE), _kw("KAPLAN-MEIER ANALYSIS", W_DEFINITIVE, ["Kaplan Meier analysis", "KM analysis"]), _kw("SURVIVAL ANALYSIS", W_STRONG), _kw("STATISTICAL INFERENCE", W_STRONG), _kw("CONFIDENCE INTERVAL", W_STRONG, ["confidence intervals"]), _kw("efficacy reports", W_STRONG), _kw("PROC LOGISTICS", W_STRONG), _kw("P-VALUE", W_MODERATE, ["p-values", "p value"]), _kw("PROC T-TEST", W_MODERATE), _kw("PHREG", W_MODERATE), _kw("LIFETEST", W_MODERATE), _kw("ANOVA", W_MODERATE), _kw("GLM", W_MODERATE), _kw("inferential", W_MODERATE), _kw("PROC MIXED", W_MODERATE), _kw("CI", W_WEAK)]),
    TaxonomyEntry(name="Figures", priority=6, activation_score=5, keywords=[_kw("KAPLAN-MEIER PLOT", W_DEFINITIVE, ["KM Plot", "KM plot", "KM Curve"]), _kw("KM plots", W_DEFINITIVE), _kw("FOREST", W_STRONG, ["Forest plot", "forest plots"]), _kw("waterfall", W_STRONG, ["waterfall plot"]), _kw("Box plots", W_STRONG, ["box plot"]), _kw("PROC template", W_MODERATE), _kw("SGPLOT", W_MODERATE), _kw("GPLOT", W_MODERATE), _kw("SUVIVAL PLOTS", W_MODERATE)]),
    TaxonomyEntry(name="crf_design_build", priority=7, activation_score=8, min_strong_keywords=1, keywords=[_kw("ecrf development", W_DEFINITIVE, ["eCRF development"]), _kw("crf design", W_DEFINITIVE, ["CRF design"]), _kw("Medidata Rave CRF build", W_DEFINITIVE), _kw("InForm CRF setup", W_DEFINITIVE), _kw("Rave Architect", W_DEFINITIVE), _kw("crf annotation", W_STRONG), _kw("crf versioning", W_STRONG), _kw("database schema design", W_STRONG), _kw("study build specifications", W_STRONG), _kw("crf implementation", W_STRONG), _kw("controlled terminology", W_STRONG), _kw("edit check programming", W_STRONG), _kw("rave edit check logic", W_STRONG), _kw("complex edit checks", W_STRONG), _kw("cross-form edit checks", W_STRONG, ["cross form edit checks"]), _kw("cross-visit edit checks", W_STRONG, ["cross visit edit checks"]), _kw("derived variables", W_MODERATE), _kw("derivations", W_MODERATE), _kw("query triggers", W_MODERATE), _kw("conditional logic", W_MODERATE), _kw("programming specifications", W_MODERATE), _kw("edit check testing", W_MODERATE), _kw("visit structure design", W_MODERATE), _kw("form configuration", W_MODERATE), _kw("repeating forms", W_MODERATE), _kw("conditional fields", W_MODERATE), _kw("data field mapping", W_MODERATE), _kw("study metadata setup", W_MODERATE), _kw("clinical data structure", W_MODERATE), _kw("field configuration", W_MODERATE), _kw("data validation rules", W_MODERATE), _kw("annotated crf", W_MODERATE), _kw("cdash", W_MODERATE), _kw("ecrf", W_MODERATE), _kw("database validation", W_MODERATE), _kw("pre-production testing", W_MODERATE), _kw("build verification", W_MODERATE), _kw("regression testing", W_WEAK), _kw("unit testing", W_WEAK), _kw("system testing", W_WEAK), _kw("auto queries", W_WEAK), _kw("logical checks", W_WEAK), _kw("range checks", W_WEAK), _kw("consistency checks", W_WEAK), _kw("custom functions", W_WEAK), _kw("edit_checks_derivations", W_WEAK), _kw("production testing", W_NOISE), _kw("uat", W_NOISE), _kw("user acceptance testing", W_NOISE)]),
    TaxonomyEntry(name="database_review_and_validation", priority=6, activation_score=5, keywords=[_kw("jreview", W_DEFINITIVE), _kw("spotfire", W_DEFINITIVE), _kw("sae reconciliation listings", W_DEFINITIVE), _kw("clinical data listings", W_STRONG), _kw("medical monitor listings", W_STRONG), _kw("data review listings", W_STRONG), _kw("raw data listings", W_STRONG), _kw("clean patient tracker", W_STRONG), _kw("patient profiles", W_MODERATE), _kw("general reconciliation listings", W_MODERATE), _kw("reconciliation listings", W_MODERATE), _kw("sas listings", W_MODERATE), _kw("manual listings", W_WEAK), _kw("visualizations", W_NOISE), _kw("python", W_NOISE)]),
    TaxonomyEntry(name="clinical_specs_documentation", priority=6, activation_score=6, keywords=[_kw("traceability matrix", W_STRONG), _kw("crf specifications", W_STRONG), _kw("database specifications", W_STRONG), _kw("edit check specifications", W_STRONG), _kw("validation plans", W_MODERATE), _kw("functional specifications", W_MODERATE), _kw("study design documents", W_MODERATE), _kw("change request documentation", W_MODERATE), _kw("version control documentation", W_MODERATE), _kw("audit documentation", W_MODERATE), _kw("build documentation", W_MODERATE), _kw("compliance documentation", W_MODERATE), _kw("validation documentation", W_MODERATE), _kw("test case creation", W_MODERATE), _kw("test scripts", W_WEAK), _kw("technical documentation", W_WEAK)]),
    TaxonomyEntry(name="edc_external_integrations", priority=6, activation_score=6, keywords=[_kw("ivrs integration", W_DEFINITIVE), _kw("irt integration", W_DEFINITIVE), _kw("epro integration", W_DEFINITIVE), _kw("ctms integration", W_DEFINITIVE), _kw("imaging data integration", W_STRONG), _kw("central lab setup", W_STRONG), _kw("external data integration", W_STRONG), _kw("lab data integration", W_STRONG), _kw("data transfer specifications", W_STRONG), _kw("vendor data transfer", W_MODERATE), _kw("api integration", W_MODERATE), _kw("third-party integrations", W_MODERATE, ["third party integrations"]), _kw("edc integrations", W_MODERATE), _kw("interface configuration", W_MODERATE), _kw("integration testing", W_MODERATE), _kw("reconciliation checks", W_MODERATE), _kw("biomarker", W_MODERATE), _kw("data imports", W_WEAK), _kw("data exports", W_WEAK)]),
    TaxonomyEntry(name="post_production_changes", priority=6, activation_score=5, keywords=[_kw("post-production changes", W_DEFINITIVE, ["post production changes"]), _kw("database change management", W_STRONG), _kw("mid-study updates", W_STRONG, ["mid study updates"]), _kw("database unlock", W_STRONG), _kw("database relock", W_STRONG), _kw("change control process", W_MODERATE), _kw("root cause analysis", W_MODERATE), _kw("defect resolution", W_MODERATE), _kw("production database support", W_MODERATE), _kw("study amendments", W_MODERATE), _kw("version upgrades", W_MODERATE), _kw("emergency fixes", W_MODERATE), _kw("impact analysis", W_WEAK), _kw("issue investigation", W_WEAK), _kw("defect tracking", W_WEAK), _kw("data discrepancies", W_WEAK), _kw("production support", W_NOISE)]),
    TaxonomyEntry(name="cross_functional_communication", priority=5, activation_score=5, keywords=[_kw("cross-functional collaboration", W_STRONG, ["cross functional collaboration"]), _kw("stakeholder communication", W_STRONG), _kw("sponsor communication", W_MODERATE), _kw("vendor coordination", W_MODERATE), _kw("data management collaboration", W_MODERATE), _kw("clinical operations interaction", W_MODERATE), _kw("requirements clarification", W_MODERATE), _kw("issue escalation", W_MODERATE), _kw("knowledge transfer", W_MODERATE), _kw("training support", W_WEAK), _kw("timeline coordination", W_WEAK), _kw("meeting participation", W_WEAK)]),
    TaxonomyEntry(name="Custom_functions", priority=7, activation_score=7, keywords=[_kw("Rave Custom Function Syntax", W_DEFINITIVE), _kw("C# Programming", W_DEFINITIVE, ["C# programming"]), _kw("Custom Function", W_STRONG), _kw("Input & Output Variable Declaration", W_STRONG), _kw("Function Parameter Handling", W_STRONG), _kw("Reusable Function Design", W_STRONG), _kw("Reusable Library Creation", W_STRONG), _kw("Cross-Form Data Access", W_STRONG), _kw("Cross-Visit Data Processing", W_STRONG), _kw("Conditional Branching", W_MODERATE), _kw("Looping Constructs", W_MODERATE), _kw("C#", W_MODERATE)]),
    TaxonomyEntry(name="protocol review", priority=6, activation_score=6, keywords=[_kw("protocol interpretation", W_STRONG), _kw("trial design review", W_STRONG), _kw("data capture strategy", W_STRONG), _kw("endpoint definition", W_STRONG), _kw("study design input", W_STRONG), _kw("protocol data flow", W_STRONG), _kw("study objectives mapping", W_STRONG), _kw("data point identification", W_MODERATE), _kw("data requirements analysis", W_MODERATE), _kw("key efficacy variables", W_MODERATE), _kw("safety variable identification", W_MODERATE), _kw("data collection requirements", W_MODERATE), _kw("CRF mapping", W_MODERATE), _kw("CRF specifications", W_WEAK)]),
    TaxonomyEntry(name="crf_acrf_design", priority=7, activation_score=6, keywords=[_kw("Medidata Rave CRF build", W_DEFINITIVE), _kw("InForm CRF setup", W_DEFINITIVE), _kw("EDC form creation", W_STRONG), _kw("dynamic form creation", W_STRONG), _kw("CRF standards (CDASH)", W_STRONG), _kw("CRF specifications document", W_STRONG), _kw("CRF layout design", W_STRONG), _kw("eCRF development", W_STRONG), _kw("CRF design", W_STRONG), _kw("CRF annotation", W_STRONG), _kw("CRF versioning", W_MODERATE), _kw("CRF QC", W_MODERATE), _kw("form edit checks", W_MODERATE), _kw("CRF validation", W_MODERATE), _kw("CRF change management", W_MODERATE)]),
    TaxonomyEntry(name="technical_specification_documents", priority=6, activation_score=7, min_strong_keywords=1, keywords=[_kw("crf design specification", W_STRONG), _kw("crf specification document", W_STRONG), _kw("ecrf design specification", W_STRONG), _kw("database design specification", W_STRONG), _kw("edit check specification", W_STRONG), _kw("edit check programming specification", W_STRONG), _kw("data validation specification", W_STRONG), _kw("controlled terminology mapping specification", W_STRONG), _kw("value-level metadata specification", W_STRONG), _kw("crf layout specification", W_MODERATE), _kw("crf build specification", W_MODERATE), _kw("annotated crf specification", W_MODERATE), _kw("crf annotation guide", W_MODERATE), _kw("ecrf build specification", W_MODERATE), _kw("ecrf development specification", W_MODERATE), _kw("form design specification", W_MODERATE), _kw("form behavior specification", W_MODERATE), _kw("module design specification", W_MODERATE), _kw("dynamic form specification", W_MODERATE), _kw("conditional field specification", W_MODERATE), _kw("manual edit check specification", W_MODERATE), _kw("validation rule specification", W_MODERATE), _kw("data cleaning rule specification", W_MODERATE), _kw("discrepancy rule specification", W_MODERATE), _kw("query rule specification", W_MODERATE), _kw("cross-form validation specification", W_MODERATE), _kw("consistency check specification", W_MODERATE), _kw("range check specification", W_MODERATE), _kw("logical rule specification", W_MODERATE), _kw("database build specification", W_MODERATE), _kw("database setup specification", W_MODERATE), _kw("database configuration specification", W_MODERATE), _kw("database update specification", W_MODERATE), _kw("data model specification", W_MODERATE), _kw("table structure specification", W_MODERATE), _kw("schema specification", W_MODERATE), _kw("interface specification", W_MODERATE), _kw("mapping specification", W_MODERATE), _kw("metadata specification", W_MODERATE), _kw("data flow specification", W_MODERATE), _kw("programmed edit check specification", W_MODERATE)]),
    TaxonomyEntry(name="database_design_build", priority=7, activation_score=6, keywords=[_kw("Rave Architect", W_DEFINITIVE), _kw("clinical database design", W_DEFINITIVE), _kw("study database release", W_STRONG), _kw("database UAT", W_STRONG), _kw("EDC configuration", W_STRONG), _kw("database build", W_STRONG), _kw("study build", W_MODERATE), _kw("database setup", W_MODERATE), _kw("database testing", W_MODERATE), _kw("database specifications", W_MODERATE), _kw("visit structure setup", W_MODERATE), _kw("metadata setup", W_MODERATE), _kw("edit check programming", W_MODERATE), _kw("data derivations", W_MODERATE), _kw("data validation rules", W_WEAK)]),
    TaxonomyEntry(name="user_acceptance_test_uat", priority=6, activation_score=5, keywords=[_kw("UAT traceability matrix", W_DEFINITIVE), _kw("UAT summary report", W_DEFINITIVE), _kw("UAT documentation", W_STRONG), _kw("UAT issue resolution", W_STRONG), _kw("test environment validation", W_STRONG), _kw("user acceptance testing", W_STRONG), _kw("test script creation", W_STRONG), _kw("test case writing", W_MODERATE), _kw("test evidence capture", W_MODERATE), _kw("database sign-off", W_MODERATE), _kw("change verification", W_MODERATE), _kw("defect logging", W_MODERATE), _kw("database testing", W_WEAK), _kw("test execution", W_WEAK), _kw("UAT", W_WEAK)]),
    TaxonomyEntry(name="external_data_integration_setup", priority=6, activation_score=6, keywords=[_kw("data transfer specifications (DTS)", W_DEFINITIVE), _kw("SAS XPT import", W_DEFINITIVE), _kw("XML data transfer", W_STRONG), _kw("ECG data import", W_STRONG), _kw("imaging data reconciliation", W_STRONG), _kw("vendor data mapping", W_STRONG), _kw("external data specifications", W_STRONG), _kw("data exchange agreement", W_STRONG), _kw("vendor data interface", W_STRONG), _kw("third-party data reconciliation", W_STRONG), _kw("data integration testing", W_STRONG), _kw("external data QC", W_MODERATE), _kw("raw data loading", W_MODERATE), _kw("EDC import", W_MODERATE), _kw("lab data integration", W_MODERATE), _kw("SAS import validation", W_MODERATE), _kw("export", W_NOISE)]),
    TaxonomyEntry(name="data_management_plan_dmp", priority=6, activation_score=5, keywords=[_kw("DMP authoring", W_DEFINITIVE), _kw("DMP review", W_DEFINITIVE), _kw("discrepancy management plan", W_DEFINITIVE), _kw("database lock procedures", W_STRONG), _kw("DMP version control", W_STRONG), _kw("DMP sign-off", W_STRONG), _kw("data flow diagram", W_MODERATE), _kw("data handling procedures", W_MODERATE), _kw("DMP updates", W_MODERATE), _kw("DMP QC", W_MODERATE), _kw("data entry conventions", W_MODERATE), _kw("coding conventions", W_MODERATE), _kw("data transfer plan", W_MODERATE), _kw("data validation plan", W_MODERATE), _kw("edit check specifications", W_WEAK)]),
    TaxonomyEntry(name="edit_check_programming", priority=7, activation_score=6, keywords=[_kw("edit check programming", W_DEFINITIVE), _kw("query automation", W_STRONG), _kw("system edit check creation", W_STRONG), _kw("rule-based validation", W_STRONG), _kw("data validation programming", W_STRONG), _kw("query trigger setup", W_MODERATE), _kw("discrepancy logic", W_MODERATE), _kw("validation logic", W_MODERATE), _kw("derivation programming", W_MODERATE), _kw("missing data flags", W_MODERATE), _kw("consistency checks", W_MODERATE), _kw("range checks", W_MODERATE), _kw("edit check specifications", W_MODERATE), _kw("edit check testing", W_WEAK), _kw("soft checks", W_WEAK), _kw("hard", W_NOISE)]),
    TaxonomyEntry(name="source_data_verfication", priority=5, activation_score=5, keywords=[_kw("CRF status monitoring", W_STRONG), _kw("site data review", W_STRONG), _kw("EDC monitoring", W_STRONG), _kw("data entry tracking", W_MODERATE), _kw("data completeness", W_MODERATE), _kw("missing data reports", W_MODERATE), _kw("data timeliness", W_MODERATE), _kw("site performance metrics", W_MODERATE), _kw("data entry metrics", W_MODERATE), _kw("site data QC", W_MODERATE), _kw("monitoring dashboard", W_MODERATE), _kw("site compliance", W_MODERATE), _kw("CRF status listing", W_MODERATE), _kw("investigator data review", W_MODERATE), _kw("data lag tracking", W_MODERATE)]),
    TaxonomyEntry(name="query_management", priority=6, activation_score=5, keywords=[_kw("DCF handling", W_DEFINITIVE), _kw("site query communication", W_STRONG), _kw("data queries log", W_STRONG), _kw("automated query rules", W_STRONG), _kw("query reconciliation", W_STRONG), _kw("query generation", W_MODERATE), _kw("query resolution", W_MODERATE), _kw("data discrepancy management", W_MODERATE), _kw("discrepancy tracking", W_MODERATE), _kw("open queries", W_MODERATE), _kw("closed queries", W_MODERATE), _kw("CRA coordination", W_MODERATE), _kw("data clarification", W_MODERATE), _kw("query metrics", W_MODERATE), _kw("data cleaning", W_MODERATE), _kw("manual data review", W_WEAK), _kw("issue tracking", W_WEAK)]),
    TaxonomyEntry(name="external_data_handling_data_reconciliation", priority=6, activation_score=6, keywords=[_kw("SAE data merge", W_DEFINITIVE), _kw("safety data reconciliation", W_STRONG), _kw("lab data reconciliation", W_STRONG), _kw("data vendor oversight", W_STRONG), _kw("external dataset management", W_STRONG), _kw("lab normal ranges", W_MODERATE), _kw("imaging data integration", W_MODERATE), _kw("data vendor QC", W_MODERATE), _kw("data transfer QC", W_MODERATE), _kw("reconciliation reports", W_MODERATE), _kw("vendor data load", W_MODERATE), _kw("vendor data import", W_MODERATE), _kw("external data review", W_MODERATE), _kw("data discrepancy analysis", W_MODERATE), _kw("SAS import validation", W_WEAK)]),
    TaxonomyEntry(name="data_listing_review", priority=5, activation_score=5, keywords=[_kw("query turnaround time", W_STRONG), _kw("data management metrics", W_STRONG), _kw("reporting automation", W_STRONG), _kw("EDC dashboards", W_MODERATE), _kw("study progress reports", W_MODERATE), _kw("site performance reports", W_MODERATE), _kw("data status dashboard", W_MODERATE), _kw("data quality metrics", W_MODERATE), _kw("cleaning metrics", W_MODERATE), _kw("issue metrics", W_MODERATE), _kw("KPI tracking", W_MODERATE), _kw("data review listings", W_MODERATE), _kw("Excel reports", W_MODERATE), _kw("SAS listings", W_WEAK), _kw("query metrics", W_WEAK)]),
    TaxonomyEntry(name="audit_readiness", priority=7, activation_score=6, keywords=[_kw("inspection readiness", W_DEFINITIVE), _kw("regulatory audit prep", W_DEFINITIVE), _kw("inspection binder", W_STRONG), _kw("audit trail review", W_STRONG), _kw("CAPA management", W_STRONG), _kw("data QC documentation", W_STRONG), _kw("internal audit participation", W_STRONG), _kw("audit response", W_MODERATE), _kw("compliance review", W_MODERATE), _kw("data integrity checks", W_MODERATE), _kw("data traceability", W_MODERATE), _kw("audit logs", W_MODERATE), _kw("quality oversight", W_MODERATE), _kw("audit closure", W_MODERATE), _kw("audit findings", W_WEAK)]),
    TaxonomyEntry(name="post_production_change", priority=6, activation_score=5, keywords=[_kw("UAT for amendment", W_DEFINITIVE), _kw("amendment impact analysis", W_STRONG), _kw("post-production update", W_STRONG, ["post production update"]), _kw("mid-study release", W_STRONG), _kw("revalidation", W_MODERATE), _kw("system update testing", W_MODERATE), _kw("migration testing", W_MODERATE), _kw("study build revision", W_MODERATE), _kw("edit check modification", W_MODERATE), _kw("database change control", W_MODERATE), _kw("CRF version update", W_MODERATE), _kw("change control log", W_MODERATE), _kw("form addition", W_WEAK), _kw("protocol amendment", W_WEAK), _kw("mid-study update", W_WEAK)]),
    TaxonomyEntry(name="data_reconciliation", priority=6, activation_score=6, keywords=[_kw("SAE reconciliation", W_DEFINITIVE), _kw("safety database cross-check", W_DEFINITIVE, ["safety database cross check"]), _kw("reconciliation closure", W_STRONG), _kw("SAE database match", W_STRONG), _kw("final reconciliation", W_STRONG), _kw("reconciliation documentation", W_STRONG), _kw("reconciliation status report", W_MODERATE), _kw("lab reconciliation", W_MODERATE), _kw("external data reconciliation", W_MODERATE), _kw("vendor data match", W_MODERATE), _kw("safety data review", W_MODERATE), _kw("reconciliation listings", W_MODERATE), _kw("data discrepancy review", W_MODERATE), _kw("vendor sign-off", W_MODERATE), _kw("data transfer QC", W_WEAK)]),
    TaxonomyEntry(name="final_documentation_audit", priority=6, activation_score=5, keywords=[_kw("study closeout binder", W_DEFINITIVE), _kw("study closeout checklist", W_DEFINITIVE), _kw("eTMF upload", W_STRONG), _kw("data management final report", W_STRONG), _kw("DMP finalization", W_STRONG), _kw("database release note", W_STRONG), _kw("documentation index", W_MODERATE), _kw("QC log archive", W_MODERATE), _kw("lock report", W_MODERATE), _kw("final listings", W_MODERATE), _kw("data management summary", W_MODERATE), _kw("DMP sign-off", W_MODERATE), _kw("documentation QC", W_MODERATE), _kw("CRF annotation final", W_MODERATE), _kw("archiving", W_WEAK)]),
    TaxonomyEntry(name="database_lock", priority=7, activation_score=5, keywords=[_kw("database lock", W_DEFINITIVE), _kw("lock readiness", W_STRONG), _kw("lock documentation", W_STRONG), _kw("database closure", W_STRONG), _kw("data freeze checklist", W_STRONG), _kw("database freeze", W_STRONG), _kw("pre-lock QC", W_STRONG), _kw("lock meeting", W_MODERATE), _kw("CRF finalization", W_MODERATE), _kw("clean file", W_MODERATE), _kw("final data cleaning", W_MODERATE), _kw("query closure", W_MODERATE), _kw("data validation completion", W_MODERATE), _kw("data freeze", W_MODERATE), _kw("system freeze", W_WEAK)]),
]

_SEP_RE, _WS_RE = re.compile(r"[-_/\\|]"), re.compile(r"\s+")
_SMART_QUOTES = str.maketrans({"\u2018": "'", "\u2019": "'", "\u201c": '"', "\u201d": '"', "\u2013": "-", "\u2014": "-", "\u00b7": " ", "\u2022": " ", "\u00a0": " "})

def normalize_text(text: str) -> str:
    return _WS_RE.sub(" ", _SEP_RE.sub(" ", unicodedata.normalize("NFC", text).translate(_SMART_QUOTES))).strip()

def _build_automaton(taxonomy: List[TaxonomyEntry]) -> Tuple[object, Dict[str, any]]:
    keyword_index = {}
    for entry in taxonomy:
        for kw_entry in entry.keywords:
            nk = normalize_text(kw_entry.keyword).lower()
            if nk and (nk not in keyword_index or keyword_index[nk]["weight"] < kw_entry.weight):
                keyword_index[nk] = {"canonical": kw_entry.keyword, "category": entry.name, "weight": kw_entry.weight, "is_syn": False, "strict": len(kw_entry.keyword.strip()) <= 3 or (kw_entry.keyword.strip().isupper() and len(kw_entry.keyword.strip()) <= 4)}
            for syn in kw_entry.synonyms:
                ns = normalize_text(syn).lower()
                if ns and (ns not in keyword_index or keyword_index[ns]["weight"] < kw_entry.weight):
                    keyword_index[ns] = {"canonical": kw_entry.keyword, "category": entry.name, "weight": kw_entry.weight, "is_syn": True, "strict": len(syn.strip()) <= 3 or (syn.strip().isupper() and len(syn.strip()) <= 4)}
    if not _AHO_AVAILABLE: return None, keyword_index
    A = ahocorasick.Automaton()
    for k, v in keyword_index.items(): A.add_word(k, (k, v))
    A.make_automaton()
    return A, keyword_index

_AUTOMATON, _KEYWORD_INDEX = _build_automaton(TAXONOMY)
_TAXONOMY_INDEX = {e.name: e for e in TAXONOMY}

def match_skills_detailed(text: str) -> List[any]:
    norm_text = normalize_text(text); norm_lower = norm_text.lower(); hits = {}
    if _AUTOMATON is not None:
        for end_idx, (norm_kw, meta) in _AUTOMATON.iter(norm_lower):
            start = end_idx - len(norm_kw) + 1
            if ((start == 0 or not norm_lower[start - 1].isalnum()) and (end_idx + 1 == len(norm_lower) or not norm_lower[end_idx + 1].isalnum())):
                if meta["strict"]:
                    pat = re.compile(r"(?<![A-Za-z0-9])" + re.escape(norm_text[start:end_idx + 1]) + r"(?![A-Za-z0-9])", re.I)
                    if not pat.search(text) and not pat.search(norm_text): continue
                hits.setdefault(meta["category"], {})[meta["canonical"]] = (meta["weight"], meta["is_syn"])
    else:
        for norm_kw, meta in _KEYWORD_INDEX.items():
            if re.search(r"(?<![A-Za-z0-9])" + re.escape(norm_kw) + r"(?![A-Za-z0-9])", norm_lower):
                hits.setdefault(meta["category"], {})[meta["canonical"]] = (meta["weight"], meta["is_syn"])

    results = []
    for cat, kw_hits in hits.items():
        entry = _TAXONOMY_INDEX[cat]; score = sum(w for w, _ in kw_hits.values()); scount = sum(1 for w, _ in kw_hits.values() if w >= 5)
        results.append(SkillMatch(category=cat, score=score, is_valid=(score >= entry.activation_score and scount >= entry.min_strong_keywords)))
    return results

@dataclass
class SkillMatch:
    category: str; score: float; is_valid: bool

def extract_skills(text: str) -> List[str]:
    return [m.category for m in match_skills_detailed(text) if m.is_valid]